name: Build & Release Firmware

on:
  push:
    tags:
      - 'v*'  # e.g., v1.0.0, v2.1.3

permissions:
  contents: write  # Needed to create releases and upload assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build with PlatformIO
        run: platformio run --environment d1_mini

      - name: Locate Firmware
        id: fw
        run: |
          BIN_FILE=$(find .pio/build/d1_mini -name "*.bin" | head -n 1)
          echo "firmware=$BIN_FILE" >> $GITHUB_OUTPUT

      - name: Upload Release Firmware
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.fw.outputs.firmware }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
